import type { Metadata } from 'next'
import GoogleMapsProvider from '~/providers/GoogleMapsProvider'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <GoogleMapsProvider>{children}</GoogleMapsProvider>
      </body>
    </html>
  )
}
